### PR TITLE
Fixes displaying with more styles and prosilver (the following)

### PR DESCRIPTION
**Pull request by Galixte**
Hi @dmzx,

adds fixes for the displaying with the other styles than prosilver: 
- FTH_Tropic: http://www.ezcom-fr.com/viewtopic.php?f=13&t=297,
- PBTech: https://github.com/PayBas/style-PBTech,
- PBWoW 3 (1 style and 12 sub-styles): https://github.com/PayBas/PBWoW3style.

update all already styles in extension with prosilver:
- Aqua-marine: http://www.ezcom-fr.com/viewtopic.php?f=13&t=332,
- Brown: http://www.ezcom-fr.com/viewtopic.php?f=13&t=337,
- iCGstation: http://www.ezcom-fr.com/viewtopic.php?f=13&t=247,
- Pro-Sub-Blue: http://www.ezcom-fr.com/viewtopic.php?f=13&t=338,
- proFormell: https://github.com/marc1706/proFormell,
- PrOrange-Black: http://www.ezcom-fr.com/viewtopic.php?f=13&t=331,
- We Universal: https://github.com/inventea/we_universal.

### CODE REVIEW

**Comment by Galixte** [comment]
It’s not ready to merge, 3 others styles will follow.

**Comment by Galixte** [comment]
Hi @dmzx,

it’s OK now, you can merge this, please.

**Comment by Galixte** [comment]
Thanks !

**Comment by dmzx** [comment]
Also you thanks!

Question:
Are the _old files not needed any more in prosilver ?

**Comment by Galixte** [comment]
Hi @dmzx,

yes, i fixed this here: https://github.com/dmzx/countdown/pull/15.

**Comment by Galixte** [comment]
Hi @dmzx,

could you merge this, please ?

**Pull request merged**
